# Generated by Django 5.0.4 on 2024-09-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpn", "0002_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="visit_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
