# Generated by Django 5.0.4 on 2024-09-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpn", "0003_site_visit_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="data_received",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="site",
            name="data_sent",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
